DELETE FROM requests;
DELETE FROM events;
DELETE FROM users;
DELETE FROM categories;
DELETE FROM locations;
DELETE FROM compilation_events;

ALTER TABLE requests ALTER COLUMN id RESTART WITH 1;
ALTER TABLE events ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE categories ALTER COLUMN id RESTART WITH 1;
ALTER TABLE locations ALTER COLUMN id RESTART WITH 1;
TRUNCATE TABLE compilations RESTART IDENTITY CASCADE;